DefaultContentLanguage = "en"
author = "lpflpf"
baseURL = "https://page.lpflpf.cn/"
copyright = """<a target="_blank" href="http://beian.miit.gov.cn/">京ICP备17037267号</a><a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502046463" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="/images/gonganbeian.png" style="float:left;"><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">京公网安备 11010502046463号</p></a>""" 
disqusShortname = "飞哥"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "G-GZD9GWLDGZ" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"
theme = "hugo-theme-tokiwa"
title = "搬砖程序员带你飞"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/noto-serif-sc-v7-latin_chinese-simplified-regular" 
description = """
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

# [taxonomies]
# category = "categories"
# series = "series"
# tag = "tags"

[social]
github = "http://github.com/lpflpf"
mail = "mailto:lipengfei634626165@163.com"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]


