baseURL: 'https://page.lpflpf.cn/'
theme: FixIt
author:
  name: lpflpf
  email: lipengfei634626165@163.com
markup:
  highlight:
    noClasses: false
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    guessSyntax: true
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
params:
  bannerFont: fonts/noto-serif-sc-v7-latin_chinese-simplified-regular
  description: ''
  enable: true
  footer:
    icp: '<a target="_blank" href="http://beian.miit.gov.cn/">京ICP备17037267号</a>'
    gov: >-
      <a target="_blank"
      href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502046463">京公网安备
      11010502046463号</a>
    hugo: false
    author: lpflpf
  app:
    iconColor : "#5bbad5"
    defaultTheme: dark
    tileColor : "#da532c"
    themeColor:
      light : "#f8f8f8"
      dark : "#252627"
  page:
    toc: #导航
      enable : true
      auto: true
      position: "right"
    comment:
      enable: false
      disqus:
        enable: true
        shortname: lpflpf
#    library:
#      js:
#        googleAdsense: >-
#          https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4191383710205711
    code:
      copy: true
      edit: false
      maxShownLines : 30
#  analytics:
#    enable: true
#    google:
#      id: "G-GZD9GWLDGZ"
#      anonymizeIP: true
  header:
    title:
      name: 搬砖程序员带你飞
      logo: /images/avatar.png
  verification:
    so: "d4de62256da7a72fa89fc026636a79e4"
  tagcloud:
    enable : true
    min : 14 # Minimum font size in px
    max : 32 # Maximum font size in px
    peakCount : 10 # Maximum count of posts per tag
    orderby : "name"

  home:
    profile:
      enable: true
      title: 搬砖程序员带你飞
      subtitle: 砖搬得多了，就能盖楼
      avatarURL: 'https://page.lpflpf.cn/images/avatar.png'
      avatarMenu: '123'
      gravatarEmail: ''
  social:
    Github: lpflpf
    Email: 'mailto:lipengfei634626165@163.com'

outputFormats:
  BaiduUrls:
    baseName: "baidu_urls"
    mediaType: "text/plain"
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - BaiduUrls


defaultContentLanguage: "zh-cn"
languages:
#  en:
#    languageName: "English"
#    languageCode : "en"
#    title : "My New Hugo FixIt Site"
#    menu:
#      main:
#        - identifier: post
#          name: Posts
#          url: /posts/
#          weight: 1
#        - identifier: tags
#          name: Tags
#          url: /tags/
#          weight: 2
#        - identifier: categories
#          name: Categories
#          url: /categories/
#          weight: 3
#        - identifier: notes
#          name: Notes
#          url: /notes/
#          weight: 4
#        - identifier: about
#          name: About
#          url: /about/
#          weight: 6
#        - identifier: Tools
#          name: Tools
#          weight: 5 
#          HasChildren: true
#        - identifier: tools
#          parent: Tools
#          url: /Tools
#          name: MyTool
#        - identifier: "curltogo"
#          parent: Tools
#          url: 'https://mholt.github.io/curl-to-go/'
#          name: curl-to-go
#          params:
#            icon: fa-brands fa-readme
#        - identifier: "jsondiff"
#          url: 'https://www.sojson.com/jsondiff.html'
#          name: jsondiff
#          parent: Tools
  zh-cn:
    hasCJKLanguage: true
    languageName: "简体中文"
    title : "搬砖程序员带你飞"
    languageCode : "zh-CN"
    menu:
      main: 
        - identifier: post
          name: 文章
          url: /posts/
          weight: 1
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 2
        - identifier: categories
          name: 分类
          url: /categories/
          weight: 3
        - identifier: notes
          name: 读书笔记 
          url: /notes/
          weight: 4
        - identifier: about
          name: 关于
          url: /about/
          weight: 6
        - identifier: Tools
          name: 工具
          weight: 5 
          HasChildren: true
        - identifier: tools
          parent: Tools
          url: /Tools
          name: 我的工具集
          weight: 1
        - identifier: "curltogo"
          parent: Tools
          url: 'https://mholt.github.io/curl-to-go/'
          name: curl-to-go
          params:
            icon: fa-solid fa-gear
          weight: 2
        - identifier: "jsondiff"
          url: 'https://www.sojson.com/jsondiff.html'
          name: jsondiff
          parent: Tools
          params:
            icon: fa-solid fa-snowflake
          weight: 3
